# Generated by Django 4.2.5 on 2023-10-05 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoTrabajoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, unique=True)),
                ('fechaPresentacion', models.DateField()),
                ('descripcion', models.TextField(max_length=500)),
                ('NroResolucionTribunal', models.CharField(max_length=15)),
                ('rolDocente', models.CharField(choices=[('DIRECTOR', 'Director'), ('CO-DIRECTOR', 'Co-Director')], max_length=12)),
                ('archivosAdjuntos', models.FileField(default=None, upload_to='Files/ArchivosDePTF/')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.alumno')),
                ('ascesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.ascesor')),
                ('docentes', models.ManyToManyField(to='persona.docente')),
            ],
            options={
                'ordering': ['fechaPresentacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientosPTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeMovimiento', models.DateTimeField()),
                ('proyectoTrabajoFinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyectotrabajofinal')),
            ],
            options={
                'ordering': ['fechaDeMovimiento'],
            },
        ),
    ]
