# Generated by Django 4.2.5 on 2023-10-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_alter_alumno_options_alter_docente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoTrabajoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, unique=True)),
                ('fechaPresentacion', models.DateField()),
                ('descripcion', models.CharField(max_length=400)),
                ('NroResolucionTribunal', models.CharField(max_length=15)),
                ('rolDocente', models.CharField(choices=[('DIRECTOR', 'Director'), ('CO-DIRECTOR', 'Co-Director'), ('ASCESOR', 'Ascesor')], max_length=12)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.alumno')),
                ('docentes', models.ManyToManyField(to='usuario.docente')),
            ],
            options={
                'ordering': ['fechaPresentacion'],
            },
        ),
    ]
