# Generated by Django 4.2.5 on 2023-10-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectotrabajofinal',
            name='archivosAdjuntos',
            field=models.FileField(default=None, upload_to='Files/ArchivosDePTF/'),
        ),
        migrations.AlterField(
            model_name='proyectotrabajofinal',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
