# Generated by Django 4.2.5 on 2023-11-01 03:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_ascesor_curriculum'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosptf',
            name='fechaVencimientoMovimiento',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='integrantesptf',
            name='fechaAlta',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='proyectotrabajofinal',
            name='ascesor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='persona.ascesor'),
        ),
        migrations.AlterField(
            model_name='proyectotrabajofinal',
            name='fechaPresentacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
