# Generated by Django 4.2.5 on 2023-11-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_movimientosptf_fechavencimientomovimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantesptf',
            name='fechaBaja',
            field=models.DateField(null=True),
        ),
    ]
