# Generated by Django 4.2.5 on 2023-11-01 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_ascesor_curriculum'),
        ('proyecto', '0004_alter_proyectotrabajofinal_ascesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectotrabajofinal',
            name='ascesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.ascesor'),
        ),
    ]
