# Generated by Django 4.2.5 on 2023-11-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_proyectotrabajofinal_tribunalevaluador_trabajo_final_and_more'),
        ('proyecto', '0008_alter_proyectotrabajofinal_nroresoluciontribunal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeevaluacionformalptf',
            name='proyectoTrabajoFinal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.proyectotrabajofinal'),
        ),
        migrations.AlterField(
            model_name='informeevaluacionptf',
            name='proyectoTrabajoFinal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.proyectotrabajofinal'),
        ),
        migrations.AlterField(
            model_name='integrantesptf',
            name='proyectoTrabajoFinal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.proyectotrabajofinal'),
        ),
        migrations.AlterField(
            model_name='movimientosptf',
            name='proyectoTrabajoFinal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.proyectotrabajofinal'),
        ),
        migrations.DeleteModel(
            name='ProyectoTrabajoFinal',
        ),
    ]
