# Generated by Django 4.2.5 on 2023-10-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre', 'apellido']},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['nombre', 'apellido']},
        ),
    ]
