# Generated by Django 4.2.5 on 2023-10-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_alumno_options_alter_docente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='correoElectronico',
            field=models.EmailField(default='son valor', max_length=256),
            preserve_default=False,
        ),
    ]
