# Generated by Django 4.2.5 on 2023-10-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunalevaluador',
            name='fechaTribunal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
