# Generated by Django 4.2.5 on 2023-10-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascesor',
            name='curriculum',
            field=models.FileField(upload_to='Files/CurriculumAscesor/'),
        ),
    ]
