# Generated by Django 4.2.5 on 2023-11-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alumno_user_ascesor_user_docente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascesor',
            name='correoElectronico',
            field=models.EmailField(max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='correoElectronico',
            field=models.EmailField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='correoElectronico',
            field=models.EmailField(max_length=256, null=True, unique=True),
        ),
    ]
