# Generated by Django 4.2.5 on 2023-11-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_ascesor_correoelectronico_docente_correoelectronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
