# Generated by Django 4.2.5 on 2023-10-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comiciondeseguimiento',
            options={'ordering': ['fechaDeComicion']},
        ),
    ]
