# Generated by Django 4.2.5 on 2023-10-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicion', '0002_alter_comiciondeseguimiento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comiciondeseguimiento',
            name='rol',
        ),
    ]
