# Generated by Django 4.2.5 on 2023-10-31 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
        ('persona', '0002_alter_ascesor_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicionDeSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroResolucion', models.CharField(max_length=15, unique=True)),
                ('fechaDeComicion', models.DateField()),
            ],
            options={
                'ordering': ['fechaDeComicion'],
            },
        ),
        migrations.CreateModel(
            name='TribunalEvaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroResolucion', models.CharField(max_length=15, unique=True)),
                ('fechaTribunal', models.DateField()),
            ],
            options={
                'ordering': ['fechaTribunal'],
            },
        ),
        migrations.CreateModel(
            name='IntegrantesTribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroResolucionTribunal', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('VOCAL_TITULAR', 'Vocal Titular'), ('VOCAL_SUPLENTE', 'Vocal Suplente')], max_length=15)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrantesComicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.docente')),
                ('nroResolucionComicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.comiciondeseguimiento')),
            ],
        ),
        migrations.CreateModel(
            name='InformeEvaluacionPTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(max_length=500)),
                ('fechaInforme', models.DateField()),
                ('estado', models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=10)),
                ('archivosAdjuntos', models.FileField(default=None, upload_to='Files/ArchivosDeInformes/')),
                ('proyectoTrabajoFinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyectotrabajofinal')),
                ('tribunalElavaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.tribunalevaluador')),
            ],
            options={
                'ordering': ['fechaInforme'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformeEvaluacionFormalPTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(max_length=500)),
                ('fechaInforme', models.DateField()),
                ('estado', models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=10)),
                ('plazoObservacion', models.DateField(blank=True, null=True)),
                ('comicionSeguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.comiciondeseguimiento')),
                ('proyectoTrabajoFinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyectotrabajofinal')),
            ],
            options={
                'ordering': ['fechaInforme'],
                'abstract': False,
            },
        ),
    ]
