# Generated by Django 4.2.5 on 2023-10-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comicion', '0003_remove_comiciondeseguimiento_rol'),
        ('proyecto', '0001_initial'),
        ('tribunal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeEvaluacionPTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInforme', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=10)),
                ('ProyectoTrabajoFinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyectotrabajofinal')),
                ('tribunalElavaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tribunal.tribunalevaluador')),
            ],
            options={
                'ordering': ['fechaInforme'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformeEvaluacionFormalPTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInforme', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=10)),
                ('descripcion', models.CharField(max_length=400)),
                ('plazoObservacion', models.DateField()),
                ('comicionSeguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicion.comiciondeseguimiento')),
                ('proyectoTrabajoFinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyectotrabajofinal')),
            ],
            options={
                'ordering': ['fechaInforme'],
                'abstract': False,
            },
        ),
    ]
