# Generated by Django 4.2.5 on 2023-10-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informeevaluacionptf',
            old_name='ProyectoTrabajoFinal',
            new_name='proyectoTrabajoFinal',
        ),
        migrations.AddField(
            model_name='informeevaluacionptf',
            name='archivosAdjuntos',
            field=models.FileField(default=None, upload_to='ArchivosDeInformes/'),
        ),
    ]
