# Generated by Django 4.2.5 on 2023-11-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_alter_integrantestribunal_nroresoluciontribunal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrantescomicion',
            old_name='nroResolucionComicion',
            new_name='comision',
        ),
    ]
