# Generated by Django 4.2.5 on 2023-10-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_rename_proyectotrabajofinal_informeevaluacionptf_proyectotrabajofinal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeevaluacionformalptf',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='informeevaluacionptf',
            name='archivosAdjuntos',
            field=models.FileField(default=None, upload_to='Files/ArchivosDeInformes/'),
        ),
    ]
