# Generated by Django 4.2.5 on 2023-11-01 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_rename_nroresolucioncomicion_integrantescomicion_comision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrantescomicion',
            old_name='comision',
            new_name='nroResolucioncomicion',
        ),
    ]
