# Generated by Django 4.2.5 on 2023-11-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_rename_comision_integrantescomicion_nroresolucioncomicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informeevaluacionptf',
            name='proyectoTrabajoFinal',
        ),
        migrations.RemoveField(
            model_name='informeevaluacionptf',
            name='tribunalElavaluador',
        ),
        migrations.DeleteModel(
            name='InformeEvaluacionFormalPTF',
        ),
        migrations.DeleteModel(
            name='InformeEvaluacionPTF',
        ),
    ]
