# Generated by Django 4.2.5 on 2023-11-11 23:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_ascesor_correoelectronico_docente_correoelectronico_and_more'),
        ('evaluacion', '0005_remove_informeevaluacionptf_proyectotrabajofinal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoTrabajoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, unique=True)),
                ('fechaPresentacion', models.DateField(default=datetime.date.today)),
                ('descripcion', models.TextField(max_length=500)),
                ('archivosAdjuntos', models.FileField(default=None, upload_to='Files/ArchivosDePTF/')),
                ('ascesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.ascesor')),
                ('coDirector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codirector', to='persona.docente')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='persona.docente')),
            ],
            options={
                'ordering': ['fechaPresentacion'],
            },
        ),
        migrations.AddField(
            model_name='tribunalevaluador',
            name='trabajo_final',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluacion.proyectotrabajofinal'),
        ),
        migrations.AlterField(
            model_name='integrantestribunal',
            name='nroResolucionTribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.proyectotrabajofinal'),
        ),
    ]
